name: data-archive-manager
channels:
  - defaults
dependencies:
  - pip=22.2.2:
    - aniso8601==9.0.1
    - attrs==22.1.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - flask==2.2.2
    - flask-restx==1.0.3
    - idna==3.4
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jsonschema==4.17.1
    - markupsafe==2.1.1
    - pyrsistent==0.19.2
    - python-dotenv==0.21.0
    - pytz==2022.6
    - pyyaml==6.0
    - requests==2.28.1
    - urllib3==1.26.13
    - werkzeug==2.2.2 